spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/cloud-mall
    username: root
    password: root
  redis:
    host: 127.0.0.1
    port: 6379
    password:
  zipkin:
    base-url: http://localhost:9411